Repository StayInLight/react-weather-app, pull requests merged in 2020-10, with the labels that each got.

#6 (#5) Создана структура папок
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/App.test.js
  src/index.css
  src/index.js
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
Labels: feature

#8 (#7) Удалил лишние файлы
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.test.js
  src/logo.svg
  src/serviceWorker.js
  src/setupTests.js
Labels: technical debt

#9 (#7) Удалил лишние импорты
  src/App.js
  src/index.js
Labels: bug

#12 (#11) Create component structure
  src/components/app/app.css
  src/components/app/app.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/components/search-bar/search-bar.css
  src/components/search-bar/search-bar.js
  src/components/weather-card/weaher-card.js
  src/components/weather-card/weather-card.css
  src/index.js
Labels: feature

#13 (#3) Создал сервис для работы с сетью
  src/components/app/app.js
  src/services/networking-service.js
Labels: feature

#17 (#5) Добавил GitHub Action, который проверяет наличие ошибок в проекте
  .github/workflows/ci.yml
Labels: technical debt

#16 (#15) Добавил базовый код для компонентов
  .gitignore
  src/components/app/app.css
  src/components/app/app.js
  src/components/navbar/navbar.css
  src/components/navbar/navbar.js
  src/components/search-bar/search-bar.css
  src/components/search-bar/search-bar.js
  src/components/weather-card/weaher-card.js
  src/components/weather-card/weather-card.css
  src/index.css
Labels: feature

#22 Добавил ESlint в проект
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  src/components/navbar/navbar.js
Labels: feature

#21 (#4) Рефакторинг сервиса weather-app
  src/components/app/app.js
  src/components/weather-card/weaher-card.js
  src/components/weather-card/weather-card.css
  src/services/networking-service.js
  src/services/weather-service.js
Labels: technical debt

#24 (#19) Добавлен сервис для отображения текущей даты
  src/components/current-date/current-date.css
  src/components/current-date/current-date.js
  src/components/weather-card/weaher-card.js
  src/services/date-formatter.js
Labels: feature

#26 (#25) Создал конфигуратор emoji
  public/index.html
  src/components/weather-card/weaher-card.js
  src/services/emoji-service.js
  src/services/weather-service.js
Labels: feature

#30 (#29) Пофиксил проблему с поломкой ESLint
  .eslintrc.json
Labels: bug

#32 (#31) Отрефакторил проект в соответстиве с eslint
  .eslintignore
  package.json
  src/components/app/app.js
  src/components/app/app.jsx
  src/components/current-date/current-date.jsx
  src/components/navbar/navbar.jsx
  src/components/weather-card/weaher-card.js
  src/services/date-formatter.js
  src/services/emoji-service.js
  src/services/networking-service.js
  src/services/weather-service.js
Labels: technical debt

#39 (#38) Добавил удаление лишних пробелов, введенных пользователем
  src/components/search-bar/search-bar.jsx
Labels: bug

#36 Реализация обработки ошибки запроса
  src/components/emoji-and-temperature/emoji-and-temperature.css
  src/components/emoji-and-temperature/emoji-and-temperature.jsx
  src/components/error-indicator/error-indicator.css
  src/components/error-indicator/error-indicator.jsx
  src/components/weather-card-content/weather-card-content.css
  src/components/weather-card-content/weather-card-content.jsx
  src/components/weather-card/weaher-card.jsx
Labels: bug

#34 (#33) Реализовал отображение погоды для полученного города
  src/components/emoji-and-temperature/emoji-and-temperature.css
  src/components/emoji-and-temperature/emoji-and-temperature.jsx
  src/components/error-indicator/error-indicator.css
  src/components/error-indicator/error-indicator.jsx
  src/components/search-bar/search-bar.js
  src/components/search-bar/search-bar.jsx
  src/components/weather-card-content/weather-card-content.css
  src/components/weather-card-content/weather-card-content.jsx
  src/components/weather-card/weaher-card.js
  src/components/weather-card/weaher-card.jsx
  src/components/weather-card/weather-card.css
Labels: feature

#47 (#40) Исправил ошибку с повторным импутом и отображением правильного header
  src/components/current-date/current-date.jsx
  src/components/weather-card-content/weather-card-content.jsx
  src/components/weather-card-header/weather-card-header.css
  src/components/weather-card-header/weather-card-header.jsx
  src/components/weather-card/weaher-card.jsx
  src/components/weather-card/weather-card.css
  src/services/weather-service.js
Labels: bug

#51 (#50) Миграция на библиотеку Ant Design
  index.css
  index.html
  package-lock.json
  package.json
  src/components/app/app.css
  src/components/app/app.jsx
  src/components/current-date/current-date.css
  src/components/current-date/current-date.jsx
  src/components/emoji-and-temperature/emoji-and-temperature.css
  src/components/emoji-and-temperature/emoji-and-temperature.jsx
  src/components/error-indicator/error-indicator.css
  src/components/error-indicator/error-indicator.jsx
  src/components/navbar/navbar.css
  src/components/navbar/navbar.jsx
  src/components/search-bar/search-bar.css
  src/components/search-bar/search-bar.jsx
  src/components/weather-card-content/weather-card-content.css
  src/components/weather-card-header/weather-card-header.css
  src/components/weather-card-header/weather-card-header.jsx
  src/components/weather-card/weaher-card.jsx
  src/components/weather-card/weather-card.css
  src/index.css
Labels: feature

#53 (#1) Создал Readme
  README.md
Labels: feature

#57 (#55) Обновил workflow на CI
  .github/workflows/ci.yml
Labels: feature

#58 (#55) Удалил лишние джобы на CI
  .github/workflows/ci.yml
Labels: feature

#62 (#61) Удалил папку assets
  assets/map-pin-solid.svg
Labels: technical debt

#52 (#46) Миграция инфраструктуры с JavaScript на Typescript
  .eslintrc.js
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  package-lock.json
  package.json
  src/components/app/app.tsx
  src/components/current-date/current-date.tsx
  src/components/emoji-and-temperature/emoji-and-temperature.css
  src/components/emoji-and-temperature/emoji-and-temperature.tsx
  src/components/error-indicator/error-indicator.css
  src/components/error-indicator/error-indicator.tsx
  src/components/navbar/navbar.tsx
  src/components/search-bar/search-bar.jsx
  src/components/search-bar/search-bar.tsx
  src/components/weather-card-content/weather-card-content.jsx
  src/components/weather-card-content/weather-card-content.tsx
  src/components/weather-card-header/weather-card-header.tsx
  src/components/weather-card/weaher-card.jsx
  src/components/weather-card/weather-card.tsx
  src/index.tsx
  src/interfaces/WeatherObject.ts
  src/services/date-formatter.js
  src/services/date-formatter.ts
  src/services/emoji-service.ts
  src/services/networking-service.js
  src/services/networking-service.ts
  src/services/weather-service.js
  src/services/weather-service.ts
  tsconfig.json
Labels: feature

#60 (#61) Обновлен Readme.md
  README.md
Labels: technical debt
